# Generated by Django 4.2.6 on 2023-10-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='school_teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.schoolteacher'),
        ),
    ]
