# Generated by Django 4.2.6 on 2024-01-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admissionform_created_at_admissionform_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='form_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webnotice',
            name='headline',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
