# Generated by Django 4.2.6 on 2024-01-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_admissionform_form_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='webNotice',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_link',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
