# Generated by Django 4.2.6 on 2024-01-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_staff_name_eng_student_name_eng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name_eng',
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='name_eng',
            field=models.CharField(default='', max_length=50),
        ),
    ]
