# Generated by Django 4.2.6 on 2024-01-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_staff_name_eng_schoolteacher_name_eng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='pi_no',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='result_file',
            field=models.FileField(null=True, upload_to='result/'),
        ),
        migrations.DeleteModel(
            name='ResultPlan',
        ),
    ]
