# Generated by Django 4.2.6 on 2024-01-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_staff_notification_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Notices',
        ),
    ]
