# Generated by Django 4.2.6 on 2024-01-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_webnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='admissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(default='', max_length=20, null=True)),
                ('form_link', models.TextField(default='', max_length=500, null=True)),
                ('class_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classes')),
            ],
        ),
    ]
