# Generated by Django 4.2.6 on 2024-01-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_admissionform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='joining_date',
        ),
    ]
